### ISSUE TITLE
Errors on restart - NoShardAvailableActionException

### ISSUE THREAD

**Issue by mahnunchik** [richardwilly98/elasticsearch-river-mongodb#120]
There are some errors on elasticsearch restart.

Ubuntu 12.04
ElasticSearch 0.90.3
MongoDB 2.4.6
elasticsearch-river-mongodb 1.6.11 from https://oss.sonatype.org/content/repositories/releases/com/github/richardwilly98/elasticsearch/elasticsearch-river-mongodb/1.6.11/elasticsearch-river-mongodb-1.6.11.zip

Full log (in the middle was called _sudo service elasticsearch restart_):

```
[2013-08-27 19:12:46,984][INFO ][node                     ] [David Cannon] version[0.90.3], pid[4838], build[5c38d60/2013-08-06T13:18:31Z]
[2013-08-27 19:12:46,989][INFO ][node                     ] [David Cannon] initializing ...
[2013-08-27 19:12:47,387][INFO ][plugins                  ] [David Cannon] loaded [river-mongodb, mapper-attachments, analysis-morphology], sites []
[2013-08-27 19:12:56,831][INFO ][node                     ] [David Cannon] initialized
[2013-08-27 19:12:56,831][INFO ][node                     ] [David Cannon] starting ...
[2013-08-27 19:12:57,443][INFO ][transport                ] [David Cannon] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.0.0.219:9300]}
[2013-08-27 19:13:00,645][INFO ][cluster.service          ] [David Cannon] new_master [David Cannon][yWqtrVO4RcuewxFeq4hJQQ][inet[/10.0.0.219:9300]], reason: zen-disco-join (elected_as_master)
[2013-08-27 19:13:00,742][INFO ][discovery                ] [David Cannon] ubuntu-test-elasticsearch/yWqtrVO4RcuewxFeq4hJQQ
[2013-08-27 19:13:00,853][INFO ][http                     ] [David Cannon] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.0.0.219:9200]}
[2013-08-27 19:13:00,853][INFO ][node                     ] [David Cannon] started
[2013-08-27 19:13:09,439][INFO ][gateway                  ] [David Cannon] recovered [1] indices into cluster_state
[2013-08-27 19:13:14,763][INFO ][cluster.metadata         ] [David Cannon] [test_photos] creating index, cause [api], shards [5]/[1], mappings [photos]
[2013-08-27 19:13:33,069][INFO ][cluster.metadata         ] [David Cannon] [_river] update_mapping [test_mongodb] (dynamic)
[2013-08-27 19:13:33,163][INFO ][river.mongodb            ] [David Cannon] [mongodb][test_mongodb] mongoServersSettings: [{port=27017, host=10.0.0.221}]
[2013-08-27 19:13:33,168][INFO ][river.mongodb            ] [David Cannon] [mongodb][test_mongodb] Server: 10.0.0.221 - 27017
[2013-08-27 19:13:33,170][INFO ][river.mongodb            ] [David Cannon] [mongodb][test_mongodb] Using mongodb server(s): host [10.0.0.221], port [27017]
[2013-08-27 19:13:33,170][INFO ][river.mongodb            ] [David Cannon] [mongodb][test_mongodb] starting mongodb stream. options: secondaryreadpreference [false], drop_collection [false], throttlesize [500], gridfs [false], filter [], db [test_photos], collection [photos], script [null], indexing to [test_photos]/[photos]
[2013-08-27 19:13:34,291][INFO ][cluster.metadata         ] [David Cannon] [_river] update_mapping [test_mongodb] (dynamic)
[2013-08-27 19:13:34,304][INFO ][river.mongodb            ] [David Cannon] [mongodb][test_mongodb] No known previous slurping time for this collection
[2013-08-27 19:13:34,604][INFO ][cluster.metadata         ] [David Cannon] [_river] update_mapping [test_mongodb] (dynamic)
[2013-08-27 19:13:34,605][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver$Indexer] Indexed 1 documents, 1 insertions 0, updates, 0 deletions, 1 documents per second
[2013-08-27 19:14:08,106][INFO ][node                     ] [David Cannon] stopping ...
[2013-08-27 19:14:08,117][INFO ][river.mongodb            ] [David Cannon] [mongodb][test_mongodb] closing mongodb stream river
[2013-08-27 19:14:08,117][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver$Indexer] Indexed 0 documents, 0 insertions 0, updates, 0 deletions, 0 documents per second
[2013-08-27 19:14:08,300][INFO ][node                     ] [David Cannon] stopped
[2013-08-27 19:14:08,301][INFO ][node                     ] [David Cannon] closing ...
[2013-08-27 19:14:08,316][INFO ][node                     ] [David Cannon] closed
[2013-08-27 19:14:12,175][INFO ][node                     ] [Poison] version[0.90.3], pid[4961], build[5c38d60/2013-08-06T13:18:31Z]
[2013-08-27 19:14:12,177][INFO ][node                     ] [Poison] initializing ...
[2013-08-27 19:14:12,517][INFO ][plugins                  ] [Poison] loaded [river-mongodb, mapper-attachments, analysis-morphology], sites []
[2013-08-27 19:14:22,470][INFO ][node                     ] [Poison] initialized
[2013-08-27 19:14:22,471][INFO ][node                     ] [Poison] starting ...
[2013-08-27 19:14:22,997][INFO ][transport                ] [Poison] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.0.0.219:9300]}
[2013-08-27 19:14:26,193][INFO ][cluster.service          ] [Poison] new_master [Poison][c6XMYuGFT1aYIiOMrGkdYQ][inet[/10.0.0.219:9300]], reason: zen-disco-join (elected_as_master)
[2013-08-27 19:14:26,229][INFO ][discovery                ] [Poison] ubuntu-test-elasticsearch/c6XMYuGFT1aYIiOMrGkdYQ
[2013-08-27 19:14:26,333][INFO ][http                     ] [Poison] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.0.0.219:9200]}
[2013-08-27 19:14:26,333][INFO ][node                     ] [Poison] started
[2013-08-27 19:14:26,433][DEBUG][action.get               ] [Poison] [_river][0]: failed to execute [[_river][test_mongodb][_meta]: routing [null]]
org.elasticsearch.action.NoShardAvailableActionException: [_river][0] null
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:123)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:72)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:47)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
    at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:92)
    at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:179)
    at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:112)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
    at org.elasticsearch.river.routing.RiversRouter$1.execute(RiversRouter.java:109)
    at org.elasticsearch.river.cluster.RiverClusterService$1.run(RiverClusterService.java:103)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
[2013-08-27 19:14:40,741][INFO ][gateway                  ] [Poison] recovered [2] indices into cluster_state
[2013-08-27 19:14:40,829][DEBUG][action.get               ] [Poison] [_river][0]: failed to execute [[_river][test_mongodb][_meta]: routing [null]]
org.elasticsearch.action.NoShardAvailableActionException: [_river][0] null
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:123)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:72)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:47)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
    at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:92)
    at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:179)
    at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:112)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
    at org.elasticsearch.river.routing.RiversRouter$1.execute(RiversRouter.java:109)
    at org.elasticsearch.river.cluster.RiverClusterService$1.run(RiverClusterService.java:103)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
[2013-08-27 19:14:41,768][DEBUG][action.get               ] [Poison] [_river][0]: failed to execute [[_river][test_mongodb][_meta]: routing [null]]
org.elasticsearch.action.NoShardAvailableActionException: [_river][0] null
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:123)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:72)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:47)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
    at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:92)
    at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:179)
    at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:112)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
    at org.elasticsearch.river.routing.RiversRouter$1.execute(RiversRouter.java:109)
    at org.elasticsearch.river.cluster.RiverClusterService$1.run(RiverClusterService.java:103)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
[2013-08-27 19:14:42,194][DEBUG][action.get               ] [Poison] [_river][0]: failed to execute [[_river][test_mongodb][_meta]: routing [null]]
org.elasticsearch.action.NoShardAvailableActionException: [_river][0] null
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:123)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:72)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:47)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
    at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:92)
    at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:179)
    at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:112)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
    at org.elasticsearch.river.routing.RiversRouter$1.execute(RiversRouter.java:109)
    at org.elasticsearch.river.cluster.RiverClusterService$1.run(RiverClusterService.java:103)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
[2013-08-27 19:14:42,398][INFO ][river.mongodb            ] [Poison] [mongodb][test_mongodb] mongoServersSettings: [{port=27017, host=10.0.0.221}]
[2013-08-27 19:14:42,398][INFO ][river.mongodb            ] [Poison] [mongodb][test_mongodb] Server: 10.0.0.221 - 27017
[2013-08-27 19:14:42,399][INFO ][river.mongodb            ] [Poison] [mongodb][test_mongodb] Using mongodb server(s): host [10.0.0.221], port [27017]
[2013-08-27 19:14:42,399][INFO ][river.mongodb            ] [Poison] [mongodb][test_mongodb] starting mongodb stream. options: secondaryreadpreference [false], drop_collection [false], throttlesize [500], gridfs [false], filter [], db [test_photos], collection [photos], script [null], indexing to [test_photos]/[photos]
```

After several messages river worked fine

**Comment by Leeyuke** [comment]
为什么？
