### ISSUE TITLE
can't get to work with external mongodb server.

### ISSUE THREAD

**Issue by c0h1b4** [richardwilly98/elasticsearch-river-mongodb#168]
Here is the command do start:

PUT _river/mongodb/_meta
{
    "type":"mongodb",
    "mongodb":{
       "servers":
            [
              { "host": "ds123456.mongolab.com", "port": 12345 }
            ],
            "credentials": [
               { "db": "pepnutri", "user": "theUser", "password": "thePassword" }
            ],
            "db": "pepnutri",
            "collection": "products"
          },
    "index": {
        "name": "testmongo",
        "type": "files"
    } 
}

here is the error:

{
            "_index": "_river",
            "_type": "mongodb",
            "_id": "_status",
            "_score": 1,
            "_source": {
               "error": "NoClassSettingsException[Failed to load class with value [mongodb]]; nested: ClassNotFoundException[mongodb]; ",
               "node": {
                  "id": "7I-UDRFKSIWRcCNouv_rvA",
                  "name": "Mercy",
                  "transport_address": "inet[/192.168.1.111:9300]"
               }
            }

here is the log:

[2013-11-12 10:53:01,480][DEBUG][action.index             ] [Mercy] Sending mapping updated to master: index [_river] type [mongodb]
[2013-11-12 10:53:01,484][INFO ][cluster.metadata         ] [Mercy] [_river] update_mapping [mongodb](dynamic)
[2013-11-12 10:53:01,487][WARN ][river                    ] [Mercy] failed to create river [mongodb][mongodb]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [mongodb]
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
        at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
        at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
        at org.elasticsearch.river.RiversService.createRiver(RiversService.java:135)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:270)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:264)
        at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: mongodb
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
        ... 9 more
[2013-11-12 10:53:01,494][DEBUG][action.index             ] [Mercy] Sending mapping updated to master: index [_river] type [mongodb]
[2013-11-12 10:53:01,498][INFO ][cluster.metadata         ] [Mercy] [_river] update_mapping [mongodb](dynamic)

Any ideas?

Thanks,
David

**Comment by akluffy** [comment]
Where is the original one
