### ISSUE TITLE
River_Stale exception

### ISSUE THREAD

**Issue by Jinkxed** [richardwilly98/elasticsearch-river-mongodb#279]
```
[DEBUG][river.mongodb.util       ] setRiverStatus called with somecollection_river - RIVER_STALE
[2014-05-27 15:17:59,238][WARN ][org.elasticsearch.river.mongodb.Slurper] Exception in slurper
org.elasticsearch.river.mongodb.Slurper$SlurperException: River out of sync with oplog.rs collection
        at org.elasticsearch.river.mongodb.Slurper.isRiverStale(Slurper.java:618)
        at org.elasticsearch.river.mongodb.Slurper.oplogCursor(Slurper.java:603)
        at org.elasticsearch.river.mongodb.Slurper.run(Slurper.java:119)
        at java.lang.Thread.run(Thread.java:744)
```

Does this mean I need to delete the data in ES and restart the river?  What other means can I go about resolving this?

**Comment by harshjari** [comment]
@richardwilly98 Could you post how to get fast initial imports? for me ~20 million documents with about 8 fields takes around 12 hours.
And i would love to improve that. Is there anything i can use to tune the import with:
"bulk": {
      "actions": ${es.bulk.actions},
      "size": ${es.bulk.size},
      "concurrent_requests": ${es.bulk.concurrent.requests},
      "flush_interval": ${es.bulk.flush.interval}
    }
?

**Comment by noorball** [comment]
@richardwilly98  I'm also having the same problem. 
Do I understand it correct, that MongoDB is writing data in the oplog file fast, but river plugin cannot keep up with that pace and MongoDB stops writing data in oplog?
If it is the case increasing the oplog.rs size is not going to solve problem permanently because next time there may be even more data. What is the cause of this problem, can river be modified to overcome it?
Any answer would be appreciated.
