### ISSUE TITLE
not authorized for query on local.system.namespaces

### ISSUE THREAD

**Issue by nsanitas** [richardwilly98/elasticsearch-river-mongodb#307]
Hi all,

Tools versions:
- MongoDB: 2.6.1 (I’m not able to change it) 
- Elasticsearch: 1.1.1 (I could change it if necessary)
  - MongoDB river plugin: master (2.0.1-SNAPSHOT)
  - mapper attachments plugin: 2.1.0-SNAPSHOT (given as being compatible with ES 1.1.1)

1/ I know it's not a good practice to use SNAPSHOT; is there a better way to use the 'master' version given as to be compatible with my version of MongoDB/ES in the MongoDB river plugin README file?

2/ I have created this river (without any problem):

``` JSON
{  
  "index": {
    "name": "logstashlogs",
    "type": "logs"
  },
  "mongodb": {
    "collection": "logs",
    "credentials": [
      {
        "db": "my_db",
        "password": "my_pwd",
        "user": "my_usr"
      }
    ],
    "db": "my_db",
    "options": {
      "drop_collection": false,
      "include_collection": true,
      "secondary_read_preference": true
    },
    "servers": [
      {
        "host": "192.168.1.201",
        "port": "27017"
      },
      {
        "host": "192.168.1.202",
        "port": "27017"
      },
      {
        "host": "192.168.1.204",
        "port": "27017"
      }
    ]
  },
  "type": "mongodb"
}
```

I precise that I'm able in MongoDB to browse _logs_ collection with the given _my_usr_ & _my_pwd_.

Problem is that no documents are indexed, and when I take a look into ES logs I’ve got this:

```
[2014-07-23 10:45:40,536][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] serverStatus returns error: not authorized on admin to execute command { serverStatus: 1, asserts: 0, backgr$
[2014-07-23 10:45:40,562][ERROR][org.elasticsearch.river.mongodb.Slurper] Mongo gave an exception
com.mongodb.MongoException: not authorized for query on local.system.namespaces
        at com.mongodb.MongoException.parse(MongoException.java:82)
        at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:292)
        at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
        at com.mongodb.DB.getCollectionNames(DB.java:400)
        at org.elasticsearch.river.mongodb.Slurper.assignCollections(Slurper.java:306)
        at org.elasticsearch.river.mongodb.Slurper.run(Slurper.java:90)
        at java.lang.Thread.run(Thread.java:744)
```

Could you help me please?
Thanks,
Nicolas

**Comment by ahmedtalhakhan** [comment]
I am running into the same problem even mongo a single instance of mongodb is running on my local machine. 
Take a look at this
https://github.com/richardwilly98/elasticsearch-river-mongodb/issues/478

**Comment by prabhu** [comment]
Tested with 2.0.6, mongodb 3.0.0 after setting is_mongos: false. Getting the below error.

[2015-03-19 09:49:50,454][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] Failed to start river mongodb-users-dev-test
com.mongodb.CommandFailureException: { "serverUsed" : "hostname:27017" , "ok" : 0.0 , "errmsg" : "not authorized on local to execute command { listCollections: \"local\" }" , "code" : 13}
        at com.mongodb.CommandResult.getException(CommandResult.java:76) 
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:140) 
        at com.mongodb.DBApiLayer.getCollectionNames(DBApiLayer.java:154)
        at org.elasticsearch.river.mongodb.MongoConfigProvider.ensureIsReplicaSet(MongoConfigProvider.java:49) 

Any ideas? Giving the user a role such as clusterAdmin etc is not an option.

**Comment by benmccann** [comment]
Yes, we ran into an auth problem with Mongo 3.0. See https://github.com/richardwilly98/elasticsearch-river-mongodb/issues/489

**Comment by prabhu** [comment]
Thank you @benmccann. Just tried with the latest 2.0.7 snapshot and still seeing the same error. I will compile my own river and update with the finding.

**Comment by prabhu** [comment]
ok, I have managed to work around this issue. It involves two steps.
1. Add read access for the search user to local database. Since you cannot create user in the local database, create this user in the main database say "mymaindb"
```
roles: [{role: "read", db: "local"}]
```
2. Specify the undocumented *auth* database in river configuration. 
```
"credentials":
    [
      { "db": "local","auth": "mymaindb'", "user": "search", "password": "search" },
    ],
```
Hope this helps.

**Comment by alexband** [comment]
@prabhu could you please help to point out how to grant roles on local?
I got errors like this
```
PRIMARY> db.grantRolesToUser("mcadmin", [{ role: "read", db: "local" }])
2015-03-31T16:01:02.023+0800 Error: getLastError command failed: write concern object cannot be empty at src/mongo/shell/db.js:1237
```

**Comment by benmccann** [comment]
It turns out we didn't entirely fix this issue in the released version. It was fixed in a recent commit: https://github.com/richardwilly98/elasticsearch-river-mongodb/commit/51bd235f7910cd01875604e89e2ba893f6425c28

**Comment by parisholley** [comment]
I am running into the same issue @prabhu has, but not of the solutions above work.

**Comment by parisholley** [comment]
I take that back, restarting the server seemed to fix it. Does the plugin cache credentials?
