### ISSUE TITLE
Support for TokuMX 2.0

### ISSUE THREAD

**Issue by benmccann** [richardwilly98/elasticsearch-river-mongodb#414]
This item is to track support for TokuMX 2.0

To test with TokuMX 2.0, update the version listed in `src/test/resources/settings.yml`

There's currently only one test failing with 2.0. To run it, use the command:

```
mvn -Dtest=RiverMongoAdvancedTransformationChildrenTest test
```

> Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 62.169 sec <<< FAILURE! - in org.elasticsearch.river.mongodb.advanced.RiverMongoAdvancedTransformationChildrenTest
> Test insert-update-delete with children attribute on TOKUMX(org.elasticsearch.river.mongodb.advanced.RiverMongoAdvancedTransformationChildrenTest)  Time elapsed: 8.567 sec  <<< FAILURE!
> java.lang.AssertionError: Test insert-update-delete with children attribute failed
>   at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
>   at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:646)
>   at org.elasticsearch.river.mongodb.advanced.RiverMongoAdvancedTransformationChildrenTest.Test insert-update-delete with children attribute(RiverMongoAdvancedTransformationChildrenTest.groovy:130)

**Comment by prabhu** [comment]
Any updates on this?

**Comment by benmccann** [comment]
Hi @prabhu, I'm focusing first on the upcoming release of [the Toku Storage Engine for MongoDB 2.8](https://github.com/Tokutek/tokumxse) before getting back to TokuMX 2.0

**Comment by prabhu** [comment]
Thank you. Looking forward for the release. Is there a way to track the pending tasks so that others could contribute quite easily and avoid creating tickets like this one?

**Comment by skotchio** [comment]
Does anybody work on this issue to be possible to work with TokuMX 2.0?
