### ISSUE TITLE
River not working in docker

### ISSUE THREAD

**Issue by tsturzl** [richardwilly98/elasticsearch-river-mongodb#454]
I'm getting a relatively useless error. I've tried installing the plugin manually and automatically(with bin/pluigin). Same result. I have no idea what the issue might be. Seems others have run mongodb-river inside of a container, however none that are of a recent version. In the logs I'm told the river fails to create, and `org.elasticsearch.common.inject.CreationException: Guice creation errors`.

This is the full output. I attempt to create 2 rivers:

```
[2015-01-24 00:16:44,023][INFO ][node                     ] [Firearm] version[1.4.2], pid[1], build[927caff/2014-12-16T14:11:12Z]
[2015-01-24 00:16:44,023][INFO ][node                     ] [Firearm] initializing ...
[2015-01-24 00:16:44,151][INFO ][plugins                  ] [Firearm] loaded [mongodb-river, mapper-attachments], sites [HQ, river-mongodb]
[2015-01-24 00:16:49,556][INFO ][node                     ] [Firearm] initialized
[2015-01-24 00:16:49,556][INFO ][node                     ] [Firearm] starting ...
[2015-01-24 00:16:49,760][INFO ][transport                ] [Firearm] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.17.0.52:9300]}
[2015-01-24 00:16:49,807][INFO ][discovery                ] [Firearm] rsstage/5N6XYjfTRSSjTryKUyVf_Q
[2015-01-24 00:16:53,584][INFO ][cluster.service          ] [Firearm] new_master [Firearm][5N6XYjfTRSSjTryKUyVf_Q][d60889c00e9d][inet[/172.17.0.52:9300]], reason: zen-disco-join (elected_as_master)
[2015-01-24 00:16:53,635][INFO ][http                     ] [Firearm] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.17.0.52:9200]}
[2015-01-24 00:16:53,635][INFO ][node                     ] [Firearm] started
[2015-01-24 00:16:53,637][INFO ][gateway                  ] [Firearm] recovered [0] indices into cluster_state
[2015-01-24 00:17:13,312][INFO ][cluster.metadata         ] [Firearm] [redef] creating index, cause [api], shards [3]/[0], mappings []
[2015-01-24 00:17:16,303][INFO ][cluster.metadata         ] [Firearm] [redef] create_mapping [articles]
[2015-01-24 00:17:16,392][INFO ][cluster.metadata         ] [Firearm] [redef] create_mapping [consumers]
[2015-01-24 00:20:03,362][INFO ][cluster.metadata         ] [Firearm] [_river] creating index, cause [auto(index api)], shards [3]/[0], mappings [articleRiver]
[2015-01-24 00:20:03,773][INFO ][cluster.metadata         ] [Firearm] [_river] update_mapping [articleRiver] (dynamic)
[2015-01-24 00:20:03,942][INFO ][cluster.metadata         ] [Firearm] [_river] update_mapping [consumerRiver] (dynamic)
[2015-01-24 00:20:04,017][WARN ][river                    ] [Firearm] failed to create river [mongodb][articleRiver]
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.IllegalArgumentException
  at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(Unknown Source)
  while locating org.elasticsearch.river.mongodb.MongoDBRiver
  while locating org.elasticsearch.river.River

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:140)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:225)
	at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:210)
	at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(MongoDBRiver.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 10 more
[2015-01-24 00:20:04,040][INFO ][cluster.metadata         ] [Firearm] [_river] update_mapping [articleRiver] (dynamic)
[2015-01-24 00:20:04,053][WARN ][river                    ] [Firearm] failed to create river [mongodb][consumerRiver]
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.IllegalArgumentException
  at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(Unknown Source)
  while locating org.elasticsearch.river.mongodb.MongoDBRiver
  while locating org.elasticsearch.river.River

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:140)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:225)
	at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:210)
	at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(MongoDBRiver.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 10 more
[2015-01-24 00:20:04,088][INFO ][cluster.metadata         ] [Firearm] [_river] update_mapping [consumerRiver] (dynamic)
[2015-01-24 00:20:04,101][WARN ][river                    ] [Firearm] failed to create river [mongodb][articleRiver]
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.IllegalArgumentException
  at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(Unknown Source)
  while locating org.elasticsearch.river.mongodb.MongoDBRiver
  while locating org.elasticsearch.river.River

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:140)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:225)
	at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:210)
	at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(MongoDBRiver.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 10 more
``

**Comment by tsturzl** [comment]
We use AWS. Could it be the VPC? Does mongodb-river open 27017?

**Comment by tsturzl** [comment]
Turns out the river settings were out of place, however the error provided isn't very useful. Perhaps some kind of validation is needed to provide a useful error.

**Comment by benmccann** [comment]
Not sure what you mean by "out of place". If you could give an example of what you did wrong and what it was when it was correct, that would help make sure that case is addressed

**Comment by tsturzl** [comment]
I had placed the "index" object inside of the "mongodb" object. 

Wrong:

```
{
	"type":"mongodb",
	"mongodb":{
		"servers":[
			{
				"host":"*.*.*.*",
				"port":27017
			}
		],
		"db":"redef-user-api",
		"collection":"redefconsumers",
        "options":{
          "exclude_fields":["hashed_password","facebook"]
        },
		"index":{
			"name":"redef",
			"type":"consumers"
		}
	}
}
```

Correct:

```
{
	"type":"mongodb",
	"mongodb":{
		"servers":[
			{
				"host":"*.*.*.*",
				"port":27017
			}
		],
		"db":"redef-user-api",
		"collection":"redefconsumers",
        "options":{
          "exclude_fields":["hashed_password","facebook"]
        }
	},
	"index":{
		"name":"redef",
		"type":"consumers"
	}
}
```
