### ISSUE TITLE
Bad installation link

### ISSUE THREAD

**Issue by Amaros90** [richardwilly98/elasticsearch-river-mongodb#461]
Hi,

I've just installed ES 1.4.2 on my computer. I also installed version 2.0.5 of the plugin and I receive this error while trying to start elasticsearch.

I also tried installing 1.3.7, but unfortunately I hit the same error again.

It seems like this issue has come up in earlier versions too, and without any good solution offered.

[2015-02-08 23:14:16,605][WARN ][plugins                  ] [Eddie Brock] plugin
 mongodb-river, failed to invoke custom onModule method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.elasticsearch.plugins.PluginsService.processModule(PluginsService
.java:199)
        at org.elasticsearch.plugins.PluginsModule.processModule(PluginsModule.j
ava:61)
        at org.elasticsearch.common.inject.Modules.processModules(Modules.java:6
4)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(Modules
Builder.java:58)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java
:197)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:203)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)

Caused by: java.lang.VerifyError: class org.elasticsearch.rest.action.mongodb.Re
stMongoDBRiverAction overrides final method handleRequest.(Lorg/elasticsearch/re
st/RestRequest;Lorg/elasticsearch/rest/RestChannel;)V
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.elasticsearch.plugin.river.mongodb.MongoDBRiverPlugin.onModule(Mo
ngoDBRiverPlugin.java:62)
        ... 13 more

**Comment by Amaros90** [comment]
I found out what the issue was.
DO NOT use the download links in the install guide section. They are outdated. Make sure you download the correct version of the plugin.

Good luck

**Comment by kdkeck** [comment]
The install guide should be fixed, then, and I think this issue should be kept open until it is.

**Comment by benmccann** [comment]
@Amaros90 can you clarify? can you share a link to the page with the bad link and which text is improperly linked?

**Comment by Amaros90** [comment]
The links in the install section are of previous version. Hope you can fix it as soon as possible...

https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki

**Comment by richardwilly98** [comment]
I will update the wiki this week-end
