### ISSUE TITLE
Failed to start river shard0 java.lang.NullPointerException

### ISSUE THREAD

**Issue by nai0om** [richardwilly98/elasticsearch-river-mongodb#468]
error code
```
[2015-02-17 04:52:09,203][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] Failed to start river shard0
java.lang.NullPointerException
	at org.elasticsearch.river.mongodb.MongoDBRiverBulkProcessor.getBulkQueueSize(MongoDBRiverBulkProcessor.java:225)
	at org.elasticsearch.river.mongodb.MongoDBRiverBulkProcessor.<init>(MongoDBRiverBulkProcessor.java:170)
	at org.elasticsearch.river.mongodb.MongoDBRiverBulkProcessor$Builder.build(MongoDBRiverBulkProcessor.java:79)
	at org.elasticsearch.river.mongodb.Indexer.getBulkProcessor(Indexer.java:94)
	at org.elasticsearch.river.mongodb.Indexer.<init>(Indexer.java:58)
	at org.elasticsearch.river.mongodb.MongoDBRiver$1.run(MongoDBRiver.java:284)
	at java.lang.Thread.run(Thread.java:745)
```

after check in source code. it's error in this function after call  info.getQueueSize().getSingles();

```
   private long getBulkQueueSize() {
        NodesInfoResponse response = client.admin().cluster().prepareNodesInfo().setThreadPool(true).get();
        for (NodeInfo node : response.getNodes()) {
            Iterator<Info> iterator = node.getThreadPool().iterator();
            while (iterator.hasNext()) {
                Info info = iterator.next();
                if ("bulk".equals(info.getName())) {
                    return info.getQueueSize().getSingles();
                }
            }
        }
        return DEFAULT_BULK_QUEUE_SIZE;
    }

```
Am i missing something in setting? 
and How can I verify this step in shell?

Thanks

**Comment by richardwilly98** [comment]
Check Elasticsearch config [1] - especially bulk thread pool

[1] - http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-threadpool.html

**Comment by nai0om** [comment]
Thanks
