### ISSUE TITLE
Can't connect to mongos for a replicated sharded cluster

### ISSUE THREAD

**Issue by fuqqer** [richardwilly98/elasticsearch-river-mongodb#469]
I get the following output from ES when trying to add a mongodb river to an elasticsearch machine.   Tried building the latest from the repo and get the same behavior.

[2015-02-18 14:17:46,362][INFO ][cluster.metadata         ] [Malice] [_river] update_mapping [testmongo] (dynamic)
[2015-02-18 14:17:46,366][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB River Plugin - version[2.0.6-SNAPSHOT] - hash[34b54d8] - time[2015-02-18T20:36:33Z]
[2015-02-18 14:17:46,366][INFO ][river.mongodb.util       ] setRiverStatus called with testmongo - RUNNING
[2015-02-18 14:17:46,368][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] River testmongo startup pending
[2015-02-18 14:17:46,369][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] Starting river testmongo
[2015-02-18 14:17:46,369][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB options: secondaryreadpreference [true], drop_collection [false], include_collection [], throttlesize [5000], gridfs [false], filter [null], db [mycollection], collection [connect_bounces], script [null], indexing to [connect_bounces]/[headers]
[2015-02-18 14:17:46,376][INFO ][cluster.metadata         ] [Malice] [_river] update_mapping [testmongo] (dynamic)
[2015-02-18 14:17:46,383][INFO ][org.elasticsearch.river.mongodb.MongoConfigProvider] MongoDB version - null
[2015-02-18 14:17:46,383][WARN ][org.elasticsearch.river.mongodb.MongoConfigProvider] serverStatus returns error: not authorized on admin to execute command { serverStatus: 1, asserts: 0, backgroundFlushing: 0, connections: 0, cursors: 0, dur: 0, extra_info: 0, globalLock: 0, indexCounters: 0, locks: 0, metrics: 0, network: 0, opcounters: 0, opcountersRepl: 0, recordStats: 0, repl: 0 }
[2015-02-18 14:17:46,396][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] Failed to start river testmongo
com.mongodb.MongoException: can't use 'local' database through mongos
	at com.mongodb.QueryResultIterator.throwOnQueryFailure(QueryResultIterator.java:246)
	at com.mongodb.QueryResultIterator.init(QueryResultIterator.java:224)
	at com.mongodb.QueryResultIterator.initFromQueryResponse(QueryResultIterator.java:184)
	at com.mongodb.QueryResultIterator.<init>(QueryResultIterator.java:62)
	at com.mongodb.DBCollectionImpl.find(DBCollectionImpl.java:86)
	at com.mongodb.DBCollectionImpl.find(DBCollectionImpl.java:66)
	at com.mongodb.DBApiLayer.getCollectionNames(DBApiLayer.java:169)
	at org.elasticsearch.river.mongodb.MongoConfigProvider.ensureIsReplicaSet(MongoConfigProvider.java:49)
	at org.elasticsearch.river.mongodb.MongoConfigProvider.getShards(MongoConfigProvider.java:134)
	at org.elasticsearch.river.mongodb.MongoConfigProvider.call(MongoConfigProvider.java:43)
	at org.elasticsearch.river.mongodb.MongoDBRiver$1.run(MongoDBRiver.java:259)
	at java.lang.Thread.run(Thread.java:745)
[2015-02-18 14:17:46,396][INFO ][river.mongodb.util       ] setRiverStatus called with testmongo - START_FAILED

**Comment by richardwilly98** [comment]
Looks like the log tells the root cause of the issue:

[2015-02-18 14:17:46,383][WARN
][org.elasticsearch.river.mongodb.MongoConfigProvider] serverStatus returns
error: not authorized on admin to execute command { serverStatus: 1,
asserts: 0, backgroundFlushing: 0, connections: 0, cursors: 0, dur: 0,
extra_info: 0, globalLock: 0, indexCounters: 0, locks: 0, metrics: 0,
network: 0, opcounters: 0, opcountersRepl: 0, recordStats: 0, repl: 0 }
