### ISSUE TITLE
Exception: Not authorized on local.system.namespaces

### ISSUE THREAD

**Issue by ahmedtalhakhan** [richardwilly98/elasticsearch-river-mongodb#478]
When using
Elasticsearch - 0.90.8
MongoDB - 2.4.8
mongodb-river - 1.7.3

I get the following exception when I try to start a river on one of my collections

    [2015-03-09 14:35:56,753][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] Starting river  testmongo
    [2015-03-09 14:35:56,757][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB River  Plugin - version[1.7.3] - hash[4ca377f] - time[2013-12-05T14:34:13Z]
    [2015-03-09 14:35:56,757][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] starting mongodb stream. options: secondaryreadpreference [false], drop_collection [false], include_collection [], throttlesize [5000], gridfs [false], filter [null], db [test_db], collection [tenant_users], script [null], indexing to [testmongo]/[users]
    [2015-03-09 14:35:56,759][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoAdminUser:  - isAuthenticated: false
    [2015-03-09 14:35:56,772][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB version - null
    [2015-03-09 14:35:56,772][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] serverStatus returns error: unauthorized
    [2015-03-09 14:35:56,787][ERROR][org.elasticsearch.river.mongodb.Slurper] Mongo gave an exception
        com.mongodb.MongoException: not authorized for query on local.system.namespaces
	at com.mongodb.MongoException.parse(MongoException.java:82)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:292)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DB.getCollectionNames(DB.java:400)
	at org.elasticsearch.river.mongodb.Slurper.assignCollections(Slurper.java:236)
	at org.elasticsearch.river.mongodb.Slurper.run(Slurper.java:75)
	at java.lang.Thread.run(Thread.java:636)
    [2015-03-09 14:36:01,792][ERROR][org.elasticsearch.river.mongodb.Slurper] Mongo gave an exception
     com.mongodb.MongoException: not authorized for query on local.system.namespaces

My river configuration looks like this

    {
    "_index": "_river",
    "_type": "testmongo",
    "_id": "_meta",
    "_version": 1,
    "exists": true,
    "_source": {
        "type": "mongodb",
        "mongodb": {
            "db": "test_db",
            "collection": "test_collection",
            "gridfs": false
        },
        "index": {
            "name": "testmongo",
            "type": "users"
        },
        "credentials": [
            {
                "db": "test_db",
                "user": "user",
                "password": "password"
            }
        ]
    }
}

The user exists in the `local` db of my mongodb instance

    > use local
    switched to db local
    > db.system.users.find()
    { "_id" : ObjectId("54fd57af5996eafccdd63255"), "user" : "user", "readOnly" : false, "pwd" :   
    "7c67ef13bbd4ca4" }

What is causing the authorization error on mongodb-river as seen in the logs above. Any help would be appreciated.

**Comment by ewgRa** [comment]
1. What is in mongodb logs?

1. Try connect via command line with such credentials to mongodb database and collection.

Seems that mongodb reject auth from elasticsearch.

**Comment by ahmedtalhakhan** [comment]
I am able to connect to mongo with these creds on the `local` database

    (elastica)[root@Talha@Fedora14 elasticsearch-0.90.8]# mongo local -u user -p password
    MongoDB shell version: 2.4.8
    connecting to: local
    >

**Comment by ewgRa** [comment]
But can you connect not to local but to test_db?

Because in your settings there is:
  "mongodb": {
        "db": "test_db",
        "collection": "test_collection",
        "gridfs": false
    },

Also what in MongoDB logs?

**Comment by ahmedtalhakhan** [comment]
Yes I am to connector to `test_db` with those credentials

**Comment by ewgRa** [comment]
Check #307, seems your case.

**Comment by ahmedtalhakhan** [comment]
@ewgRa this seems to be a fix in a much alter version of mongodb-river. Cant I get 1.7.3 to work?

**Comment by ewgRa** [comment]
Can't say.

"The river execute a serverStatus command", I think this is a key for your problem. River can't execute it, because haven't rights. Make this possible and maybe this will work.
