### ISSUE TITLE
Issue in filtering 

### ISSUE THREAD

**Issue by mlecoq** [richardwilly98/elasticsearch-river-mongodb#485]
Hi,

I would like to add a filter in my river configuration.

I have made a query like this : 
`db.mydatabase.find({ "parutions.parutionrubriques.rubrique.codan9": {"$in": [ "00000734", "00000736", "00000737"] } })`

and it worked fine.

I have tried the following solutions in river configuration:

# First one 

`"filter": "{"parutions.parutionrubriques.rubrique.codan9": {"$in": [ "00000734", "00000736", "00000737"] } }"`

An exception has occured on parsing:

org.elasticsearch.index.mapper.MapperParsingException: failed to parse
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:563)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:413)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:189)
....
Caused by: org.elasticsearch.common.jackson.core.JsonParseException: Unexpected character ('p' (code 112)): was expecting comma to separate OBJECT entries
 at [Source: [B@2ff558ba; line: 29, column: 19]
	at org.elasticsearch.common.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)

# Second one

I thought it was due to $in operator:
 `"filter": "{ "parutions.parutionrubriques.rubrique.codan9":  "00000734" }"`

Same exception

# Third one

Without the quotes:

`"filter": { "parutions.parutionrubriques.rubrique.codan9": {"$in": [ "00000734", "00000736", "00000737"] } }`

1) Error injecting constructor, com.mongodb.util.JSONParseException: 
{parutions.parutionrubriques.rubrique.codan9={$in=[00000734, 00000736, 00000737]}}
                                                             ^
  at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(Unknown Source)
  while locating org.elasticsearch.river.mongodb.MongoDBRiver
  while locating org.elasticsearch.river.River

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)

Thanks,
Mickael.

**Comment by ewgRa** [comment]
From https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki/MongoDB-custom-filter

"Filter value should be prefix by o. because of the structure of the document in oplog.rs collection. More details available here 2."

Try it with first one, maybe this is a reason.

**Comment by mlecoq** [comment]
Hi,

thanks for your reply.

Yes I tried to prefix with o, but the same issue occured:
Caused by: com.mongodb.util.JSONParseException: 
{o.parutions.parutionrubriques.rubrique.codan9={$in=[00000734, 00000736, 00000737]}}
                                                               ^
	at com.mongodb.util.JSONParser.read(JSON.java:290)
	at com.mongodb.util.JSONParser.parseObject(JSON.java:248)
	at com.mongodb.util.JSONParser.parse(JSON.java:213)
	at com.mongodb.util.JSONParser.parse(JSON.java:163)

**Comment by ewgRa** [comment]
Can you show configuration and whole exception text?

**Comment by mlecoq** [comment]
Sure !

Here is the whole stacktrace: 

``
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, com.mongodb.util.JSONParseException: 
{o.parutions.parutionrubriques.rubrique.codan9={$in=[00000734, 00000736, 00000737]}}
                                                               ^
  at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(Unknown Source)
  while locating org.elasticsearch.river.mongodb.MongoDBRiver
  while locating org.elasticsearch.river.River

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:140)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mongodb.util.JSONParseException: 
{o.parutions.parutionrubriques.rubrique.codan9={$in=[00000734, 00000736, 00000737]}}
                                                               ^
	at com.mongodb.util.JSONParser.read(JSON.java:290)
	at com.mongodb.util.JSONParser.parseObject(JSON.java:248)
	at com.mongodb.util.JSONParser.parse(JSON.java:213)
	at com.mongodb.util.JSONParser.parse(JSON.java:163)
	at com.mongodb.util.JSON.parse(JSON.java:99)
	at com.mongodb.util.JSON.parse(JSON.java:79)
	at org.elasticsearch.river.mongodb.MongoDBRiverDefinition.addRemovePrefix(MongoDBRiverDefinition.java:866)
	at org.elasticsearch.river.mongodb.MongoDBRiverDefinition.removePrefix(MongoDBRiverDefinition.java:849)
	at org.elasticsearch.river.mongodb.MongoDBRiverDefinition.parseSettings(MongoDBRiverDefinition.java:744)
	at org.elasticsearch.river.mongodb.MongoDBRiver.<init>(MongoDBRiver.java:139)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 10 more

``

**Comment by mlecoq** [comment]
Here is the configuration

curl -XPUT "localhost:9200/_river/my_river/_meta" -d '{
  "index": {
    "name": "sle01",
    "type": "blocsepj",
    "bulk": {
      "concurrent_requests": 10,
      "flush_interval": "1000ms",
      "actions": 50,
      "size": "100mb"
    }
  },
  "mongodb": {
    "db": "<db>",
    "servers": [
      {
        "port": <port>,
        "host": "<host>"
      }
    ],
    "credentials": [
      {
        "db": "admin",
        "password": "csp",
        "user": "csp"
      }
    ],
    "collection": "blocepj",
    "script": "ctx.id = ctx.document.blocepjid; ctx.document._id = ctx.document.blocepjid;if (ctx.document.inscriptions.inscription[0].adresse != undefined && ctx.document.inscriptions.inscription[0].adresse.geoloc != undefined && ctx.document.inscriptions.inscription[0].adresse.geoloc.lat != undefined) { ctx.document.proGeoCoord = { lat: 0+ctx.document.inscriptions.inscription[0].adresse.geoloc.lat, lon: 0+ctx.document.inscriptions.inscription[0].adresse.geoloc.long }; } else { ctx.document.proGeoCoord = { lat: 0, lon: 0 }; }",
    "filter": { "o.parutions.parutionrubriques.rubrique.codan9": {"$in": [ "00000734", "00000736", "00000737"] } },
    "options": {
      "include_fields": ["blocepjid", "intlprincipal", "epj.denom", "epj.numvoie", "epj.libvoie", "epj.cp", "epj.libloc", "intitule.denom", "inscriptions.inscription", "parutions.parutionrubriques.rubrique"],
      "skip_initial_import": false
    }
  },
  "type": "mongodb"
}'

**Comment by ewgRa** [comment]
try 

"filter": "{ \"o.parutions.parutionrubriques.rubrique.codan9\": {\"$in\": [ \"00000734\", \"00000736\", \"00000737\"] } }",

**Comment by mlecoq** [comment]
I tried to escape the double quotes and I have now this error

```
{"error":"MapperParsingException[failed to parse]; nested: JsonParseException[Unexpected character ('\\' (code 92)): was expecting either valid name character (for unquoted name) or double-quote (for quoted) to start field name\n at [Source: [B@5afcdaa4; line: 29, column: 18]]; ","status":400}
```

**Comment by ewgRa** [comment]
Can you show configuration?

Pay attention not only to double quotes, but also to "filter": **"** quotes

**Comment by mlecoq** [comment]
You're right, I didn't notice the double quote around. The river is now created. I am checking if the filter has been taken into account.

**Comment by mlecoq** [comment]
It looks fine, thanks a lot !

**Comment by ewgRa** [comment]
Your welcome, I create issue to ask change wiki, seems there is an escaping error.
Please close this issue is all is fine.
