### ISSUE TITLE
Failed to parse

### ISSUE THREAD

**Issue by ArnaudValensi** [richardwilly98/elasticsearch-river-mongodb#486]
It seems there is a bug parsing my nested type. 'argument' is a mixed type. Any solution ?

```
[2015-03-16 13:14:54,697][DEBUG][action.bulk              ] [Thunderbolt] [mindup][4] failed to execute bulk item (index) index {[mindup][events][5502f98f7ca11d2f1e418a37], sourc
e[{"argument":{"msg":"Not enough points"},"timestamp":"2015-03-13T14:51:59.598Z","category":"server","_id":"5502f98f7ca11d2f1e418a37","__v":0,"action":"error500"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [argument.msg]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:709)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:500)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:557)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:413)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:435)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NumberFormatException: For input string: "Not enough points"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
        at java.lang.Long.parseLong(Long.java:483)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
        at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:300)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:235)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
        ... 14 more
[2015-03-16 13:14:54,728][ERROR][org.elasticsearch.river.mongodb.MongoDBRiverBulkProcessor] Bulk processor failed. failure in bulk execution:
[6]: index [mindup], type [events], id [5502f98f7ca11d2f1e418a37], message [MapperParsingException[failed to parse [argument.msg]]; nested: NumberFormatException[For input string: "Not enough points"]; ]
```

**Comment by ewgRa** [comment]
Seems that one field have different type. For mongodb it is ok, but in ES each field have type.

Try use 'script' and transform mixed to needed format yourself.

https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki#script-filters

Maybe this help you. Another way to exclude this field from indexing.

**Comment by ArnaudValensi** [comment]
I think the error was a bug, but I didn't need this field, so your answer is working. So do exluding the field using the option in the river.
