### ISSUE TITLE
2.0.6 version doesn't support new authentication mechanism (SCRAM) for MongoDB 3.0.0

### ISSUE THREAD

**Issue by svezzoli** [richardwilly98/elasticsearch-river-mongodb#489]
I have installed new version 3.0.0 for MongoDB and new version 2.0.6 for elasticsearch-river-mongodb plugin, but it seems that river-mongodb plugin does not support the new user authentication mechanism (SCRAM) for MongoDB 3.0.0. 

My plugin configuration is:
curl -XPUT "localhost:9200/_river/nfmkpi_current/_meta" -d '
{
  "type": "mongodb",
  "mongodb": { 
    "servers":
    [ { "host": "localhost" , "port": 27017 } ],
	
    "credentials":
    [ { "db": "admin", "user": "nfmoss", "password": "nfmoss" } ],
	
	"db": "nfmkpi", 
    "collection": "current"
  },
  "index": { 
      "name": "kpi-metrics-sync", 
      "type": "kpi-sync"
  }
}'

The new mongodb nfmoss user has been created by default with following credentials:

{ "_id" : "admin.nfmoss", "user" : "nfmoss", "db" : "admin", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "LBxj2gyLmY77Cd0LAQNrGg==", "storedKey" : "guJ0L/0JSb2UcOUUYTaAfkR+yWA=", "serverKey" : "FXUAEBDmtkNUuazB5Cm2ia6N1+8=" } }, "roles" : [ { "role" : "readWriteAnyDatabase", "db" : "admin" }, { "role" : "userAdminAnyDatabase", "db" : "admin" } ] }

The start of river-mongodb plugin fails for following reason:

[2015-03-16 16:50:48,709][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] Failed to start river nfmkpi_current
com.mongodb.CommandFailureException: { "serverUsed" : "nfmoss:27017" , "ok" : 0.0 , "errmsg" : "auth failed" , "code" : 18}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
	at com.mongodb.DBPort$NativeAuthenticator.authenticate(DBPort.java:986)
	at com.mongodb.DBPort.authenticate(DBPort.java:432)
	at com.mongodb.DBPort.checkAuth(DBPort.java:443)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:289)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:269)
	at com.mongodb.DBCollectionImpl.find(DBCollectionImpl.java:84)
	at com.mongodb.DB.command(DB.java:320)
	at com.mongodb.DB.command(DB.java:299)
	at com.mongodb.DB.command(DB.java:388)
	at org.elasticsearch.river.mongodb.MongoConfigProvider.isMongos(MongoConfigProvider.java:90)
	at org.elasticsearch.river.mongodb.MongoConfigProvider.call(MongoConfigProvider.java:42)
	at org.elasticsearch.river.mongodb.MongoDBRiver$1.run(MongoDBRiver.java:259)
	at java.lang.Thread.run(Unknown Source)
[2015-03-16 16:50:48,711][INFO ][river.mongodb.util       ] setRiverStatus called with nfmkpi_current - START_FAILED

The recommendation is that all client code needs to have createMongoCRCredential replaced with createCredential in order to authenticate with SCRAM-SHA-1 mechanism (3.0.0 server version), but I still see the method createMongoCRCredential in MongoClientService.java.

**Comment by benmccann** [comment]
Fix checked in here: https://github.com/richardwilly98/elasticsearch-river-mongodb/commit/732ba35d5c2faeb427663200e55c1d4c5acf828d

I suppose we should probably cut a release with this fix. Perhaps @richardwilly98 would be so kind? :-)

**Comment by richardwilly98** [comment]
The last automated build was successful - SNAPSHOT can be find here: https://drone.io/github.com/richardwilly98/elasticsearch-river-mongodb/files/target/releases/elasticsearch-river-mongodb-2.0.7-SNAPSHOT.zip

I will make a new release this week-end.

**Comment by benmccann** [comment]
Thanks Richard!

**Comment by svezzoli** [comment]
Thanks.
I will test the 2.0.7 SNAPSHOT and I will give you a feedback.

**Comment by svezzoli** [comment]
I tested 2.0.7 SNAPSHOT both with legacy MONGOCR credentials and with new SCRAM-SHA-1 credentials and all is OK.

**Comment by richardwilly98** [comment]
Version 2.0.7 has been released.

**Comment by benmccann** [comment]
Thanks Richard!
