### ISSUE TITLE
Not creati from a remote Mongo instance

### ISSUE THREAD

**Issue by marlonoso** [richardwilly98/elasticsearch-river-mongodb#492]
I'm hitting this issue when trying to sync documents from a remote Mongo instance:
This is my configuration:

curl -XPUT 'http://localhost:9200/_river/mongodb/_meta' -d '{
"type": "mongodb",
"mongodb": {
"servers":
[
{ "host": "a.some.public.ip", "port": 27017 }
],
"db": "social_client",
"collection": "social_mention_event"
},

"index": {
  "name": "client",
  "type": "social"
}
}'

* Remote Mongo server does not use authentication
* I can *telnet a.some.public.ip 27017* from ES host
* I'm doing a *tcpdump port 27017* on a.some.public.ip
* It shows a little traffic when restarting ES after setting the afore mentioned config. Then traffic stops
* Meanwhile, ES logs:

[2015-03-19 14:42:30,403][INFO ][http ] [Vampire by Night] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.247.68:9200]}
[2015-03-19 14:42:30,403][INFO ][node ] [Vampire by Night] started
[2015-03-19 14:42:30,922][INFO ][gateway ] [Vampire by Night] recovered [2] indices into cluster_state
[2015-03-19 14:42:31,439][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB River Plugin - version[2.0.6] - hash[3c38a8a] - time[2015-03-10T03:06:51Z]
[2015-03-19 14:42:31,441][INFO ][river.mongodb.util ] setRiverStatus called with mongodb - RUNNING
[2015-03-19 14:42:31,450][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] River mongodb startup pending
[2015-03-19 14:42:31,455][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] Starting river mongodb
**[2015-03-19 14:42:31,456][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB options: secondaryreadpreference [false], drop_collection [false], include_collection [], throttlesize [5000], gridfs [false], filter [null], db [social_client], collection [social_mention_event], script [null], indexing to [client]/[social]**
[2015-03-19 14:42:31,458][INFO ][river.mongodb ] [Vampire by Night] Creating MongoClient for [[66.45.229.186:27017]]

Then
*curl -XGET 'http://localhost:9200/client/_mapping' *
shows nothing
*{"client":{"mappings":{}}}*

**Comment by ewgRa** [comment]
Go to http://elasticsearchhost:9200/_plugin/river-mongodb/ and delete river if it is exists.

Install river, go to http://elasticsearchhost:9200/_plugin/river-mongodb/ which one status it have? Running?
Go to http://elasticsearchhost:9200/_plugin/river-mongodb/ and stop this river, what you have in logs about this stop (after "Creating MongoClient for" log)?

**Comment by ewgRa** [comment]
Also as remove ip of server from your first message if you wary about it.

**Comment by ewgRa** [comment]
Also as enable please TRACE level: https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki#troubleshooting

**Comment by marlonoso** [comment]
Following your suggested steps
* Deleted the river
* Installed
* Stopped river
* Log after Stop:

[2015-03-20 10:32:39,845][INFO ][river.mongodb.util       ] setRiverStatus called with mongodb - STOPPED
[2015-03-20 10:32:40,583][INFO ][org.elasticsearch.river.mongodb.StatusChecker] About to stop river: mongodb
[2015-03-20 10:32:40,583][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] Stopping river mongodb
[2015-03-20 10:32:40,584][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] Stopped river mongodb
[2015-03-20 10:32:40,585][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] Failed to start river mongodb
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.elasticsearch.river.mongodb.MongoDBRiver$1.run(MongoDBRiver.java:262)
	at java.lang.Thread.run(Thread.java:745)
[2015-03-20 10:32:40,587][INFO ][river.mongodb.util       ] setRiverStatus called with mongodb - START_FAILED

**Comment by marlonoso** [comment]
I enabled TRACE
Then I restarted ES and:

[2015-03-20 10:47:14,282][INFO ][node                     ] [Collector] version[1.4.4], pid[5339], build[c88f77f/2015-02-19T13:05:36Z]
[2015-03-20 10:47:14,282][INFO ][node                     ] [Collector] initializing ...
[2015-03-20 10:47:14,291][INFO ][plugins                  ] [Collector] loaded [mongodb-river], sites [river-mongodb]
[2015-03-20 10:47:16,148][TRACE][rest.action.mongodb      ] [Collector] RestMongoDBRiverAction - baseUrl: /_river/mongodb
[2015-03-20 10:47:16,235][INFO ][node                     ] [Collector] initialized
[2015-03-20 10:47:16,241][INFO ][node                     ] [Collector] starting ...
[2015-03-20 10:47:16,367][INFO ][transport                ] [Collector] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.247.68:9300]}
[2015-03-20 10:47:16,389][INFO ][discovery                ] [Collector] elasticsearch/Phf8MLwuTAWBtLWRdPV01Q
[2015-03-20 10:47:20,158][INFO ][cluster.service          ] [Collector] new_master [Collector][Phf8MLwuTAWBtLWRdPV01Q][easysol][inet[/ES.host.ip.address:9300]], reason: zen-disco-join (elected_as_master)
[2015-03-20 10:47:20,185][INFO ][http                     ] [Collector] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/ES.host.ip.address:9200]}
[2015-03-20 10:47:20,185][INFO ][node                     ] [Collector] started
[2015-03-20 10:47:20,776][INFO ][gateway                  ] [Collector] recovered [2] indices into cluster_state
[2015-03-20 10:47:21,389][TRACE][org.elasticsearch.river.mongodb.MongoDBRiver] Initializing river : [mongodb]
[2015-03-20 10:47:21,390][TRACE][river.mongodb            ] Parse river settings for mongodb
[2015-03-20 10:47:21,393][TRACE][river.mongodb            ] mongoServersSettings: [{port=27017, host=mongo.server.ip.address}]
[2015-03-20 10:47:21,393][TRACE][river.mongodb            ] Server: mongo.server.ip.address - 27017
[2015-03-20 10:47:21,407][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB River Plugin - version[2.0.6] - hash[3c38a8a] - time[2015-03-10T03:06:51Z]
**[2015-03-20 10:47:21,409][ERROR][org.elasticsearch.river.mongodb.MongoDBRiver] Cannot start river mongodb. Current status is START_FAILED**

**Comment by ewgRa** [comment]
> java.lang.InterruptedException: sleep interrupted
Seems this is #470 and connection problem. Try from your ES server connect to mongo server via mongo client, like

mongo {{host}}/social_client
mongo {{host}}/admin
mongo {{host}}/local

And show output

**Comment by marlonoso** [comment]
marlon@easysol:~/app/social_client/elasticsearch-1.4.4/config$ mongo mongo.remote.ip.address/social_client
MongoDB shell version: 3.0.1
connecting to: mongo.remote.ip.address/social_client
Server has startup warnings: 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
rs0:PRIMARY> exit
bye
marlon@easysol:~/app/social_client/elasticsearch-1.4.4/config$ mongo mongo.remote.ip.address/admin
MongoDB shell version: 3.0.1
connecting to: mongo.remote.ip.address/admin
Server has startup warnings: 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
rs0:PRIMARY> exit
bye
marlon@easysol:~/app/social_client/elasticsearch-1.4.4/config$ mongo mongo.remote.ip.address/local
MongoDB shell version: 3.0.1
connecting to: mongo.remote.ip.address/local
Server has startup warnings: 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-03-17T12:41:57.788-0400 I CONTROL  [initandlisten] 
rs0:PRIMARY> exit

**Comment by ewgRa** [comment]
Ok, there is need more research on it, logs which one queries river try to run. When I will have time, I will try to solve #470, I think problem there. But unfortunately, I don't know when it happens. Try solve it yourself, or maybe wait river author to fix it.

**Comment by ewgRa** [comment]
Check this file https://github.com/ewgRa/elasticsearch-river-mongodb/blob/debug/manual-testing/collect-debug-info.sh . Change parameters in the begining of file to your real params.

Upload it to server, where is elasticsearch runs. Run under elasticsearch user like:
"sudo -u elasticsearch sh collect-debug-info.sh", copy this command and output to file debug.txt.

Post debug.txt to gist  - https://gist.github.com/ and give here a link.

**Comment by marlonoso** [comment]
=========== Me =======
ES_HOME=/home/marlon/app/redit/elasticsearch-1.4.4
ES_HOST=localhost
ES_PORT=9200
MONGODB_HOST=ip.ip.ip.ip
MONGODB_PORT=27017
MONGODB_DATABASE=social_client
MONGODB_COLLECTION=social_mention_event

echo "=========== Me ======="
cat $0
echo
echo "=========== Elasticsearch version ======="
curl -XGET $ES_HOST:$ES_PORT
echo
echo "=========== Elasticsearch process ======="
ps -aux | grep elasticsearch
echo
echo "=========== Elasticsearch mongodb rivers ======="
curl -XGET $ES_HOST:$ES_PORT/_river/mongodb/list
echo
echo
echo "=========== Replica set configuration ======="
mongo $MONGODB_HOST:$MONGODB_PORT --eval "printjson(rs.conf())"
echo
echo "=============== Replica set status =========="
mongo $MONGODB_HOST:$MONGODB_PORT --eval "printjson(rs.status())"
echo
echo "=============== River plugin version =========="
ls $ES_HOME/plugins/river-mongodb
echo
echo "=============== Mongo client version =========="
mongo --version
echo
echo "=============== Mongo server version =========="
mongo --eval "db.version()"
echo
echo "===================== isMaster? ============="
mongo $MONGODB_HOST:$MONGODB_PORT/admin --eval "printjson(db.isMaster())"
echo
echo "===================== oplog ============="
mongo $MONGODB_HOST:$MONGODB_PORT/local --eval "printjson(db.oplog.rs.findOne())"
echo
echo "===================== Mongodb collection ============="
mongo $MONGODB_HOST:$MONGODB_PORT/$MONGODB_DATABASE --eval "printjson(db.$MONGODB_COLLECTION.findOne())"

=========== Elasticsearch version =======
{
  "status" : 200,
  "name" : "Agamemnon",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}

=========== Elasticsearch process =======
marlon    1019 50.1  1.7 4558760 282288 pts/7  Sl+  13:24   0:11 /usr/lib/jvm/java-8-oracle/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.foreground=yes -Des.path.home=/home/marlon/app/redit/elasticsearch-1.4.4 -cp :/home/marlon/app/redit/elasticsearch-1.4.4/lib/elasticsearch-1.4.4.jar:/home/marlon/app/redit/elasticsearch-1.4.4/lib/*:/home/marlon/app/redit/elasticsearch-1.4.4/lib/sigar/* org.elasticsearch.bootstrap.Elasticsearch
root      1105  0.0  0.0  15956   920 pts/15   S+   13:25   0:00 grep elasticsearch

=========== Elasticsearch mongodb rivers =======
{"hits":1,"pages":1.0,"count":1,"page":1,"results":[{"settings":{"index":{"name":"redit","type":"social"},"type":"mongodb","mongodb":{"servers":[{"port":27017,"host":"ip.ip.ip.ip"}],"collection":"social_mention_event_REDIT","db":"redit"}},"lastTimestamp":null,"indexCount":0,"name":"mongodb","status":"START_FAILED"}]}

=========== Replica set configuration =======
MongoDB shell version: 3.0.1
connecting to: ip.ip.ip.ip:27017/test
{
	"_id" : "rs0",
	"version" : 1,
	"members" : [
		{
			"_id" : 0,
			"host" : "pci-analyzer:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : 0,
			"votes" : 1
		}
	],
	"settings" : {
		"chainingAllowed" : true,
		"heartbeatTimeoutSecs" : 10,
		"getLastErrorModes" : {
			
		},
		"getLastErrorDefaults" : {
			"w" : 1,
			"wtimeout" : 0
		}
	}
}

=============== Replica set status ==========
MongoDB shell version: 3.0.1
connecting to: ip.ip.ip.ip:27017/test
{
	"set" : "rs0",
	"date" : ISODate("2015-03-25T18:25:34.589Z"),
	"myState" : 1,
	"members" : [
		{
			"_id" : 0,
			"name" : "pci-analyzer:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 697417,
			"optime" : Timestamp(1426624225, 11608),
			"optimeDate" : ISODate("2015-03-17T20:30:25Z"),
			"electionTime" : Timestamp(1426610517, 1),
			"electionDate" : ISODate("2015-03-17T16:41:57Z"),
			"configVersion" : 1,
			"self" : true
		}
	],
	"ok" : 1
}

=============== River plugin version ==========
elasticsearch-river-mongodb-2.0.6.jar
guava-17.0.jar
mongo-java-driver-2.13.0.jar
_site

=============== Mongo client version ==========
MongoDB shell version: 3.0.1

=============== Mongo server version ==========
MongoDB shell version: 3.0.1
connecting to: test
3.0.1

===================== isMaster? =============
MongoDB shell version: 3.0.1
connecting to: ip.ip.ip.ip:27017/admin
{
	"setName" : "rs0",
	"setVersion" : 1,
	"ismaster" : true,
	"secondary" : false,
	"hosts" : [
		"pci-analyzer:27017"
	],
	"primary" : "pci-analyzer:27017",
	"me" : "pci-analyzer:27017",
	"electionId" : ObjectId("550859551d2e5a5717fd3e7f"),
	"maxBsonObjectSize" : 16777216,
	"maxMessageSizeBytes" : 48000000,
	"maxWriteBatchSize" : 1000,
	"localTime" : ISODate("2015-03-25T18:25:34.928Z"),
	"maxWireVersion" : 3,
	"minWireVersion" : 0,
	"ok" : 1
}

===================== oplog =============
MongoDB shell version: 3.0.1
connecting to: ip.ip.ip.ip:27017/local
{
	"ts" : Timestamp(1425998688, 1),
	"h" : NumberLong(0),
	"v" : 2,
	"op" : "n",
	"ns" : "",
	"o" : {
		"msg" : "initiating set"
	}
}

===================== Mongodb collection =============
MongoDB shell version: 3.0.1
connecting to: ip.ip.ip.ip:27017/social_client
{
	"_id" : "0000158758ffaf595a4c384aa57a53c4",
	"_class" : "net.mycompany.dbms.dto.socialmentions.SocialMentionsEvent",
	"clientId" : "MY_CLIENT",
	"provider" : "MY_PROVIDER",
	"source" : "twitter",
	"queryText" : "Ecatepec",
	"title" : "Cae en Ecatepec distribuidor de pornografía infantil http://t.co/O07tpht9Zk",
	"description" : "Cae en Ecatepec distribuidor de pornografía infantil http://t.co/O07tpht9Zk",
	"dateProviderCaptured" : ISODate("2014-05-19T10:47:00Z"),
	"dateEventAdded" : ISODate("2014-05-19T15:39:16.624Z"),
	"url" : "https://twitter.com/anglimadys1/statuses/468402484860710912",
	"transparentData" : "{\"id\":\"0000158758ffaf595a4c384aa57a53c4\",\"title\":\"Cae en Ecatepec distribuidor de pornografía infantil http://t.co/O07tpht9Zk\",\"source\":\"Twitter\",\"published\":\"10:47am Mon May 19 2014\",\"url\":\"https://twitter.com/anglimadys1/statuses/468402484860710912\",\"influence\":\"NA\",\"content\":\"Cae en Ecatepec distribuidor de pornografía infantil http://t.co/O07tpht9Zk\",\"sentiment\":0}",
	"forReport" : false,
	"checked" : false,
	"influence" : 0,
	"sentiment" : 0,
	"withImage" : false
}

**Comment by marlonoso** [comment]
Hi
https://gist.github.com/marlonoso/533df96d8fbd514e8675#file-es-debug-info-log

**Comment by ewgRa** [comment]
Ok, on first view seems all is fine, but there is some questions.

In your river configuration you have:
          "collection": "social_mention_event_REDIT",
          "db": "redit"

But in test script you point:
MONGODB_DATABASE=social_client
MONGODB_COLLECTION=social_mention_event

1. Why there is a difference?

2. Can you provide output for real settings? Fix your river configuration if it is wrong, or fix script parameters.

3. Did you run it under elasticsearch user?

**Comment by ewgRa** [comment]
Also from "px ax" result:
marlon    1019 50.1  1.7 4558760 282288 pts/7  Sl+  13:24   ...

Your elastic search runs under marlon user? Can you run then script under this user?
sudo -u marlon ...

**Comment by marlonoso** [comment]
1. There is no difference, I masked the configuration on test script
2. But now that real settings are visible: https://gist.github.com/marlonoso/8163f764231966a1103c#file-es-collect-debug-info-log (under marlon user)
3. I didn't. ES is installed via zip
