### ISSUE TITLE
Authentication failed for MongoDB 3.0.3

### ISSUE THREAD

**Issue by RicherdLee** [richardwilly98/elasticsearch-river-mongodb#529]
I spent 2 days in sync data from the remote mongodb,but i failed。
Elasticsearch 1.4.2
elasticsearch 2.0.9
MondoDB 3.0.3
mongo-java-driver-2.13.1.jar
This is my configuration:
curl -XPUT "localhost:9200/_river/my_river_mongodb/_meta" -d '
{
"type": "mongodb",
"mongodb": {
    "host": "ip",
    "port": "27017",
    "credentials": [
            {
                "db": "admin",
                "user": "root",
                "password": "admin"
            }
        ],
    "db": "admin"
},
"index": {
    "name": "river_mongodb"
} 
}'

Mongodb credentials:
{
  "_id": "admin.root",
  "user": "root",
  "db": "admin",
  "credentials": {
    "SCRAM-SHA-1": {
      "iterationCount": 10000,
      "salt": "wX418oC/hp4P+x4ciV/lIg==",
      "storedKey": "ardGMlbvkvj7Iv993wg2WOcg62Q=",
      "serverKey": "nz7DaKt+N/q2XJo5S11UgFNd64U="
    }
  },
  "roles": [
    {
      "role": "__system",
      "db": "admin"
    }
  ]
}

My MongoDB Cluster：
Route:  ip:27014
ip:20000,ip:200001

ES logs:
[2015-05-25 08:05:05,106][INFO ][cluster.metadata         ] [esnode0] [_river] creating index, cause [auto(index api)], shards [1]/[1], mappings [my_river_mongodb]
 [2015-05-25 08:05:05,294][INFO ][cluster.metadata         ] [esnode0] [_river] update_mapping [my_river_mongodb] (dynamic)
[2015-05-25 08:05:05,299][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB River Plugin - version[2.0.9] - hash[73ddea5] - time[2015-04-06T21:16:46Z]
[2015-05-25 08:05:05,300][INFO ][river.mongodb.util       ] setRiverStatus called with my_river_mongodb - RUNNING
 [2015-05-25 08:05:05,302][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] River my_river_mongodb startup pending
[2015-05-25 08:05:05,303][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] Starting river my_river_mongodb
[2015-05-25 08:05:05,303][INFO ][org.elasticsearch.river.mongodb.MongoDBRiver] MongoDB options: secondaryreadpreference [false], drop_collection [false], include_collection [], throttlesize [5000], gridfs [false], filter [null], db [admin], collection [my_river_mongodb], script [null], indexing to [river_mongodb]/[admin]
 [2015-05-25 08:05:05,344][INFO ][cluster.metadata         ] [esnode0] [river_mongodb] creating index, cause [api], shards [5]/[1], mappings []
 [2015-05-25 08:05:05,495][INFO ][org.elasticsearch.river.mongodb.MongoConfigProvider] MongoDB version - 3.0.3
 [2015-05-25 08:05:05,498][INFO ][cluster.metadata         ] [esnode0] [_river] update_mapping [my_river_mongodb] (dynamic)
 [2015-05-25 08:05:05,502][WARN ][org.elasticsearch.river.mongodb.MongoDBRiver] Failed to start river my_river_mongodb
 com.mongodb.CommandFailureException: { "serverUsed" : "ip:20000" , "ok" : 0.0 , "code" : 18 , "errmsg" : "Authentication failed." , "$gleStats" : { "lastOpTime" : { "$ts" : 0 , "$inc" : 0} , "electionId" : { "$oid" : "55629bb7c16f34a4e43c6342"}}}
at com.mongodb.CommandResult.getException(CommandResult.java:76)
at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
 at com.mongodb.DBPort$SaslAuthenticator.authenticate(DBPort.java:899)
at com.mongodb.DBPort.authenticate(DBPort.java:432)
at com.mongodb.DBPort.checkAuth(DBPort.java:443)
at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:289)
at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:269)
at com.mongodb.DBCollectionImpl.find(DBCollectionImpl.java:84)
at com.mongodb.DB.command(DB.java:320)
at com.mongodb.DB.command(DB.java:299)
at com.mongodb.DB.command(DB.java:388)
at com.mongodb.DBApiLayer.getCollectionNames(DBApiLayer.java:152)
at org.elasticsearch.river.mongodb.MongoConfigProvider.ensureIsReplicaSet(MongoConfigProvider.java:49)
at org.elasticsearch.river.mongodb.MongoConfigProvider.getShards(MongoConfigProvider.java:126)
at org.elasticsearch.river.mongodb.MongoConfigProvider.call(MongoConfigProvider.java:43)
at org.elasticsearch.river.mongodb.MongoDBRiver$1.run(MongoDBRiver.java:259)
at java.lang.Thread.run(Thread.java:745)
2015-05-25 08:05:05,502][INFO ][river.mongodb.util       ] setRiverStatus called with my_river_mongodb - START_FAILED

Thanks

**Comment by akluffy** [comment]
Elasticsearch 1.4.2
elasticsearch 2.0.9

?
