### ISSUE TITLE
failed to create river [mongodb]

### ISSUE THREAD

**Issue by linhaobuaa** [richardwilly98/elasticsearch-river-mongodb#533]
[2015-06-05 22:07:53,827][WARN ][river                    ] [ubuntu6] failed to create river [mongodb][guba_post_600001]
161243 org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [mongodb]
161244 ▸---at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
161245 ▸---at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
161246 ▸---at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
161247 ▸---at org.elasticsearch.river.RiversService.createRiver(RiversService.java:137)
161248 ▸---at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:273)
161249 ▸---at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:267)
161250 ▸---at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
161251 ▸---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
161252 ▸---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
161253 ▸---at java.lang.Thread.run(Thread.java:745)
161254 Caused by: java.lang.ClassNotFoundException: mongodb
161255 ▸---at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
161256 ▸---at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
161257 ▸---at java.security.AccessController.doPrivileged(Native Method)
161258 ▸---at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
161259 ▸---at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
161260 ▸---at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
161261 ▸---at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
161262 ▸---at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
161263 ▸---... 9 more

**Comment by ewgRa** [comment]
Can you attach river configuration and versions of software?

**Comment by linhaobuaa** [comment]
put /_river/guba_post_600001/_meta
{
  "type": "mongodb",
  "mongodb": {
    "servers": [
      {
        "host": "219.224.135.94",
        "port": "27020"
      }
    ],
    "db": "guba",
    "collection": "post_stock_600001"
  },
  "index": {
    "name": "guba",
    "type": "post_stock_600001"
  }
}

**Comment by ewgRa** [comment]
Versions of ES, MongoDB and river plugin?

Does river plugin installed?

**Comment by linhaobuaa** [comment]
elasticsearch 1.5.2
river 2.0.9
mongodb 2.4.14

**Comment by ewgRa** [comment]
Check versions table at https://github.com/richardwilly98/elasticsearch-river-mongodb/blob/master/README.md

Also in ES 1.5 rivers is deprecated, can't say is plugin support this version, don't try it yet.

Maybe plugin author can say more about ES 1.5 support and his plans.

**Comment by ewgRa** [comment]
I think big chance that you have problems because of unsupported/incompatibled versions.

**Comment by linhaobuaa** [comment]
OK, so appreciated for the suggestion.
