### ISSUE TITLE
I am trying to use the MongoDB river (v2.0.11) with elasticsearch (v1.7.3) , can't sync data to elasticsearch

### ISSUE THREAD

**Issue by chenyishun** [richardwilly98/elasticsearch-river-mongodb#584]
I am trying to use the MongoDB river (v2.0.11) with elasticsearch (v1.7.3) , can't sync data to elasticsearch
error log:

```
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [mongodb]
    at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
    at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
    at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
    at org.elasticsearch.river.RiversService.createRiver(RiversService.java:138)
    at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:274)
    at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:268)
    at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: mongodb
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
    ... 9 more
[2016-07-06 08:52:45,070][INFO ][cluster.metadata         ] [Sauron] [_river] update_mapping [person] (dynamic)
```

**Comment by 4ndrew** [comment]
See #576
