### ISSUE TITLE
com.mongodb.MongoException: can't find a master

### ISSUE THREAD

**Issue by calebjclark** [richardwilly98/elasticsearch-river-mongodb#69]
I'm trying to get elasticsearch-river-mongodb running on my local development environment. I successfully set up a replica set with three mongo instances, but elasticsearch is not returning results. The following is in my elasticsearch logs:

```
[2013-04-25 12:09:43,397][INFO ][river.mongodb            ] [Patriot I] [mongodb][mongodb] mongoServersSettings: [{port=27017, host=127.0.0.1}]
[2013-04-25 12:09:43,397][INFO ][river.mongodb            ] [Patriot I] [mongodb][mongodb] Server: 127.0.0.1 - 27017
[2013-04-25 12:09:43,399][INFO ][river.mongodb            ] [Patriot I] [mongodb][mongodb] Using mongodb server(s): host [127.0.0.1], port [27017]
[2013-04-25 12:09:43,399][INFO ][river.mongodb            ] [Patriot I] [mongodb][mongodb] starting mongodb stream. options: secondaryreadpreference [true], throttlesize [500], gridfs [false], filter [], db [testmongo], script [null], indexing to [mongoindex]/[person]
[2013-04-25 12:09:43,507][WARN ][river                    ] [Patriot I] failed to create river [mongodb][mongodb]
com.mongodb.MongoException: can't find a master
    at com.mongodb.DBTCPConnector.checkMaster(DBTCPConnector.java:518)
    at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:277)
    at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:257)
    at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:310)
    at com.mongodb.DB.command(DB.java:274)
    at com.mongodb.DB.command(DB.java:256)
    at com.mongodb.DB.command(DB.java:313)
    at com.mongodb.DB.command(DB.java:211)
    at org.elasticsearch.river.mongodb.MongoDBRiver.isMongos(MongoDBRiver.java:458)
    at org.elasticsearch.river.mongodb.MongoDBRiver.start(MongoDBRiver.java:422)
    at org.elasticsearch.river.RiversService.createRiver(RiversService.java:146)
    at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:270)
    at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:264)
    at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:87)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
```

When I run rs.status() from the mongo console the replication seems to be setup correctly:

```
{
    "set" : "rs0",
    "date" : ISODate("2013-04-25T16:19:22Z"),
    "myState" : 1,
    "members" : [
        {
            "_id" : 0,
            "name" : "MacBookPro:27017",
            "health" : 1,
            "state" : 1,
            "stateStr" : "PRIMARY",
            "uptime" : 4252,
            "optime" : {
                "t" : 1366906502,
                "i" : 1
            },
            "optimeDate" : ISODate("2013-04-25T16:15:02Z"),
            "self" : true
        },
        {
            "_id" : 1,
            "name" : "MacBookPro:27018",
            "health" : 1,
            "state" : 2,
            "stateStr" : "SECONDARY",
            "uptime" : 4245,
            "optime" : {
                "t" : 1366906502,
                "i" : 1
            },
            "optimeDate" : ISODate("2013-04-25T16:15:02Z"),
            "lastHeartbeat" : ISODate("2013-04-25T16:19:20Z"),
            "lastHeartbeatRecv" : ISODate("2013-04-25T16:19:21Z"),
            "pingMs" : 0,
            "syncingTo" : "MacBookPro:27017"
        },
        {
            "_id" : 2,
            "name" : "MacBookPro:27019",
            "health" : 1,
            "state" : 2,
            "stateStr" : "SECONDARY",
            "uptime" : 4245,
            "optime" : {
                "t" : 1366906502,
                "i" : 1
            },
            "optimeDate" : ISODate("2013-04-25T16:15:02Z"),
            "lastHeartbeat" : ISODate("2013-04-25T16:19:20Z"),
            "lastHeartbeatRecv" : ISODate("2013-04-25T16:19:22Z"),
            "pingMs" : 0,
            "syncingTo" : "MacBookPro:27017"
        }
    ],
    "ok" : 1
}
```

I have installed and uninstalled elasticsearch as well as river-mongodb with no improvement. I have also spent hours googling for fixes. Any thoughts?

**Comment by ximendatie** [comment]
I had the same problem and then closed and open the network which make it work again.😅
